# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination basted on number of posts
exclude: ["node_modules", "doc", "Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
pygments: true
repository: https://github.com/kaen/wasabi
baseurl: /wasabi
